<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>gdoc</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~G</string>
    <key>name</key>
    <string>Grails Doc (Gdoc)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>text.html.textile</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.grails.gdoc</string>
    <key>uuid</key>
    <string>2a58560f-2a3b-4fab-b429-44535ce270bc</string>
</dict>
</plist>
