<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gsp</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Grails Server Page (GSP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;%--</string>
			<key>comment</key>
			<string>JSP style comments</string>
			<key>end</key>
			<string>--%&gt;</string>
			<key>name</key>
			<string>comment.block.html.jsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>%{--</string>
			<key>comment</key>
			<string>GSP comments</string>
			<key>end</key>
			<string>--}%</string>
			<key>name</key>
			<string>comment.block.html.gsp</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-groovy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-js</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#html</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>embedded-groovy</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\$\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.embedded.begin.groovy</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Groovy embedded in ${}</string>
					<key>contentName</key>
					<string>source.groovy.embedded.html.gsp</string>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.embedded.end.groovy</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#groovy</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>&lt;%(?:\=|!|@)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.embedded.begin.groovy</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Groovy embedded in &lt;% %&gt;, &lt;%! %&gt;, &lt;%= %&gt;, or &lt;%@ %&gt;</string>
					<key>contentName</key>
					<string>source.groovy.embedded.html.gsp</string>
					<key>end</key>
					<string>%&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.embedded.end.groovy</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#groovy</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>embedded-js</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=(&lt;(?i:g:javascript)&gt;))</string>
					<key>comment</key>
					<string>Javascript embedded in &lt;g:javascript /&gt;</string>
					<key>end</key>
					<string>(?&lt;=&lt;/g:javascript&gt;)</string>
					<key>name</key>
					<string>source.js.embedded.html.gsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-groovy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=(&lt;(?i:r:script)))</string>
					<key>comment</key>
					<string>Javascript embedded in &lt;r:script /&gt;</string>
					<key>end</key>
					<string>(?&lt;=&lt;/r:script&gt;)</string>
					<key>name</key>
					<string>source.js.embedded.html.gsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-groovy</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#html</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>groovy</key>
		<dict>
			<key>comment</key>
			<string>Groovy modified for GSPs</string>
			<key>include</key>
			<string>source.groovy.gsp</string>
		</dict>
		<key>html</key>
		<dict>
			<key>comment</key>
			<string>HTML modified for GSPs</string>
			<key>include</key>
			<string>text.html.basic.gsp</string>
		</dict>
		<key>js</key>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.gsp</string>
	<key>uuid</key>
	<string>64fa00ff-9506-4cf4-ad0c-896802a23385</string>
</dict>
</plist>
